### ISSUE TITLE
Problem: Classes don't show up, no classes timetables

### ISSUE THREAD

**Issue by new-on-github** [Perflyst/OpenUntis#12] opened 2018-09-14 06:33 UTC
I cannot use the Classes timetables. There is no list like in the "teachers"-menu. Maybe it's an issue with my configuration, but in the webuntis online interface the classes list is working fine.

**Comment by Perflyst** [comment] 2018-09-15 09:57
Does it work in the official Untis app?

**Comment by Perflyst** [comment] 2018-09-20 17:58
I cannot reproduce your issue, please tell me if it is working in official Untis app. It could be that your school blocked access to other classes. The mobile apps uses another API than the webuntis dashboard.

**Comment by steelstrings** [comment] 2018-09-26 17:02
I'm having the same issue. It is however working in the official Untis app. Furthermore whereas I can just view my class via the webuntis dashboard, I can view all classes of the school via the official app.

**Comment by new-on-github** [comment] 2019-01-22 19:39
In the new version (2.1.0) the bug seems to be gone. I can see classes now. Thanks for your work!

If @steelstrings cannot reproduce the problem anymore too, we can close this.

**Comment by steelstrings** [comment] 2019-01-24 18:04
Version 2.1.0 solves this problem for me too. I can access now all classes, just like with the official app. We can close this issue.

**Comment by Perflyst** [comment] 2019-01-24 18:22
There was no change about how this works in the app, see all changes here: https://github.com/Perflyst/OpenUntis/releases/tag/v2.1.0

I wonder how this got solved, anyway nice to hear!

**Closed by Perflyst** 2019-01-24 18:22 UTC
Labels: not reproducible
